### ISSUE TITLE
Why Float64 are converted to Float32?

### ISSUE THREAD

**Issue by lasalillo** [SpaceMusicZH/VL.IO.AbletonLink#1]
This is not really an Issue,
Would it be possible to provide Float64 values by Default? 
at least for Beat and Phase. In some situations Float32 is not precise enough.

**Comment by bj-rn** [comment]
It's Float32 because we are using it like this in our workflow and it is kind of "standard" in vvvv/vl. Have you actually had problems with Float32 coming from Link?

**Comment by lasalillo** [comment]
For all my music prototypes in Gamma i'm using Float64 as clock source because sometimes i have to subdivide the clock phase and convert it to Integers in order to do certain operations, and in some situations Float32 doesn't provide enough resolution.

I think, if the API provides Float64 it's for a reason and it should be accesible independently of your main usecase. 

At least provide a way to expose those parameters, it doesn't need to be the default output. 

Thanks

**Comment by bj-rn** [comment]
Added Link (Float64 Advanced). The Nuget should be available soonish.

**Comment by lasalillo** [comment]
Cool, Thanks bj-rn
